% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/old_pals.R
\docType{data}
\name{university of California, Santa Barbara}
\alias{uni_california_1}
\title{Main colors of the University of California}
\format{
  An object of class \code{character} of length 5.
}
\source{
  Color definitions are based on 
  \url{https://brand.ucsb.edu/visual-identity/color}.
  }
  \usage{
    uni_california_1
  }
  \value{
    A named vector of colors (HEX/HTML codes of type character).
  }
  \description{
    \code{uni_california_1} provides the basic or main colors 
    of the \href{https://www.ucsb.edu}{University of California}, USA
  }
  \details{
    The color \code{navy} is alternatively defined as 
    \code{RGB 0/54/96}, \code{HEX #003660}. 
      
      The color \code{gold} is alternatively defined as 
      \code{RGB 254/188/17}, \code{HEX #FEBC11}. 
        
        The color \code{Light grey darken 80} is alternatively defined as 
        \code{RGB 17/ 21/ 23}, \code{HEX #111517}. 
          
          The color \code{Light gray} is alternatively defined as 
          \code{RGB 220/ 225/ 229}, \code{HEX #DCE1E5}. 
            
            The color \code{White} is alternatively defined as 
            \code{RGB 255/ 255/ 255}, \code{HEX #FFFFFF}. 
              
              The color \code{Sea green web} is alternatively defined as 
              \code{RGB 9/ 132/ 122}, \code{HEX #09847A}. 
                
                The color \code{Aqua web} is alternatively defined as 
                \code{RGB 4/ 124/ 145}, \code{HEX #047C91}. 
                  
                  The color \code{Moss web} is alternatively defined as 
                  \code{RGB 109/ 125/ 51}, \code{HEX#6D7D33}.    
                    
                    The color \code{Coral} is alternatively defined as 
                    \code{RGB 239/ 86/ 69}, \code{HEX #EF5645}.
                      
                      The color \ code{Clay} is alternatively defined as 
                      \code{RGB 220/ 214/ 204}, \code{HEX #DCD6CC}. 
                        
                        The color \ code{Sandstone} is alternatively defined as 
                        \code{RGB 201/ 191/ 157}, \code{HEX#C9BF9D}. 
                          
                          The color \ code{Mist} is alternatively defined as 
                          \code{RGB 156/ 190/ 190}, \code{HEX #9CBEBE}. 
                            
                            The color \ code{Dark Coral} is alternatively defined as 
                            \code{RGB 196/ 52/ 36}, \code{HEX #C43424}. 
                              
                              The color \ code{Light Clay} is alternatively defined as 
                              \code{RGB 241/ 238/ 234}, \code{HEX #F1EEEA}. 
                                
                                The color \ code{Light Sandstone} is alternatively defined as 
                                \code{RGB 237/ 234/ 223}, \code{HEX #EDEADF}. 
                                  
                                  The color \ code{Light Mist} is alternatively defined as 
                                  \code{RGB 218/ 230/ 230}, \code{HEX #DAE6E6}. 
        
       
          See the \code{\link{ac}} and \code{\link{usecol}} functions for creating color gradients.
        }
        \examples{
          uni_california_1
          unikn::seecol(uni_california_1, main = "Main colors of the University of California")
          unikn::demopal(uni_california_1, type = 1, 
                         main = "Main colors of California University")
          
          # 5-color gradient:
          uni_california_5 <- unikn::usecol(c(uni_california_1["navy"], "white"), n = 6)[1:5]
          
        }
        \seealso{
          \code{\link{uni_ulm_2}} for the departmental accent colors of the University of Ulm;  
          \code{\link{seecol}} for viewing and comparing color palettes; 
          \code{\link{usecol}} for using color palettes; 
          \code{\link{simcol}} for finding similar colors; 
          \code{\link{newpal}} for defining new color palettes; 
          \code{\link{grepal}} for finding named colors.
          
          Other university color palettes: 
            \code{\link{CMU_1_core}},
          \code{\link{CMU_2_tartan}},
          \code{\link{CMU_3_campus}},
          \code{\link{UCLA_1}},
          \code{\link{UCLA_2}},
          \code{\link{UCLA_3}},
          \code{\link{UCSD_1_core}},
          \code{\link{UCSD_2_accent}},
          \code{\link{UCSD_3_neutral}},
          \code{\link{berkeley_1}},
          \code{\link{berkeley_2}},
          \code{\link{caltech_1}},
          \code{\link{caltech_2}},
          \code{\link{caltech_3}},
          \code{\link{chicago_1}},
          \code{\link{chicago_2}},
          \code{\link{columbia}},
          \code{\link{cornell_1}},
          \code{\link{cornell_2}},
          \code{\link{cornell_3_accent}},
          \code{\link{duke_1}},
          \code{\link{duke_2}},
          \code{\link{eth_pal_1}},
          \code{\link{eth_pal_2}},
          \code{\link{eth_pal_3}},
          \code{\link{fu_pal_0}},
          \code{\link{fu_pal_1}},
          \code{\link{fu_pal_2}},
          \code{\link{fu_pal_3}},
          \code{\link{harvard_1}},
          \code{\link{harvard_2}},
          \code{\link{harvard_3_accent}},
          \code{\link{hu_pal_1}},
          \code{\link{hu_pal_2}},
          \code{\link{jhu_0}},
          \code{\link{jhu_1}},
          \code{\link{jhu_2}},
          \code{\link{jhu_3_accent}},
          \code{\link{jhu_4_gray}},
          \code{\link{lmu_pal_1}},
          \code{\link{lmu_pal_2}},
          \code{\link{lmu_pal_3}},
          \code{\link{michigan_1}},
          \code{\link{michigan_2}},
          \code{\link{mit_pal}},
          \code{\link{monash_1}},
          \code{\link{monash_2}},
          \code{\link{mpg_pal}},
          \code{\link{northwestern_1}},
          \code{\link{northwestern_2}},
          \code{\link{nyu_1}},
          \code{\link{nyu_2}},
          \code{\link{nyu_accent}},
          \code{\link{nyu_neutral}},
          \code{\link{princeton_0}},
          \code{\link{princeton_1}},
          \code{\link{princeton_2}},
          \code{\link{rpi_pal_1}},
          \code{\link{rpi_pal_2}},
          \code{\link{rpi_pal_3}},
          \code{\link{rptu_pal}},
          \code{\link{stanford_1}},
          \code{\link{stanford_2_accent}},
          \code{\link{stanford_3_web}},
          \code{\link{toronto_1}},
          \code{\link{uni_bonn_1}},
          \code{\link{uni_bonn_2}},
          \code{\link{uni_freiburg_0}},
          \code{\link{uni_freiburg_1}},
          \code{\link{uni_freiburg_2}},
          \code{\link{uni_freiburg_blue}},
          \code{\link{uni_freiburg_br}},
          \code{\link{uni_freiburg_grey}},
          \code{\link{uni_freiburg_info}},
          \code{\link{uni_goettingen_1}},
          \code{\link{uni_goettingen_2}},
          \code{\link{uni_goettingen_3}},
          \code{\link{uni_hamburg_1}},
          \code{\link{uni_hamburg_2}},
          \code{\link{uni_jena_1}},
          \code{\link{uni_jena_2}},
          \code{\link{uni_kiel_1}},
          \code{\link{uni_kiel_2}},
          \code{\link{uni_koeln_1}},
          \code{\link{uni_koeln_2}},
          \code{\link{uni_konstanz_1}},
          \code{\link{uni_konstanz_2}},
          \code{\link{uni_mannheim_1}},
          \code{\link{uni_mannheim_2}},
          \code{\link{uni_pal_1}},
          \code{\link{uni_regensburg_1}},
          \code{\link{uni_regensburg_2}},
          \code{\link{uni_regensburg_3}},
          \code{\link{uni_stuttgart_1}},
          \code{\link{uni_stuttgart_2_print}},
          \code{\link{uni_ulm_2}},
          \code{\link{upenn_1}},
          \code{\link{upenn_2}},
          \code{\link{yale_1}}
        }
        \author{
          \strong{unicol}, 2023-06-28.
        }
        \concept{university color palettes}
        \keyword{datasets}
        
